version: 2.0
jobs:
    build:
      docker:
        - image: circleci/buildpack-deps:stretch

      steps:
        - checkout
        - setup_remote_docker

        - run:
            name: Build Docker image
            command: docker build -t samirsilwal/test-ui:latest .


workflows:
    version: 2
    build-master:
      jobs:
        - build:
            filters:
               branches:
                  only: master