version: 2.0
jobs:
    build:
      docker:
        - image: samirsilwal/test-ui:0.0.1

      steps:
        - checkout
        - run:
            name: install curl
            command: apt-get install curl
        - run:
            name: install docker
            command: |
                set -x
                VER="18.06.3-ce"
                curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
                tar -xz -C /tmp -f /tmp/docker-$VER.tgz
                mv /tmp/docker/* /usr/bin

        - run:
            name: Build Docker image
            command: docker build -t samirsilwal/test-ui:latest 