version: 2.0
jobs:
    build:
      docker:
        - image: samirsilwal/test-ui:0.0.1

      steps:
        - checkout
        - run:
            name: install docker
            command: apt-get install -y docker.io
        - run:
            name: Build Docker image
            command: docker build -t samirsilwal/test-ui:latest 