version: 2.0
jobs:
    build:
      docker:
        - image: samirsilwal/test-ui:0.0.1

      steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
        - run:
            name: Build Docker image
            command: docker build -t samirsilwal/test-ui:latest 